### ISSUE TITLE
Option to specify path to elm?

### ISSUE THREAD

**Issue by botandrose** [fbonetti/ruby-elm-compiler#1]
Howdy! I've hooked Elm up to my Rails app using your gem, and all the pieces are in place and working great. However, for various reasons I can't always `sudo npm -g install elm` on every place this Rails app is being deployed, so I'd like to be able to specify the path to the elm executable. Something like:

``` ruby
Elm::Compiler(file_path, nil, 'node_modules/.bin/elm')
```

What do you think? If you're amenable to this idea, I could put together a pull request.

**Comment by fbonetti** [comment]
Couldn't you just add `elm-make` to your path?

**Comment by botandrose** [comment]
Yeah, that solution would definitely work!

However, I have opinions on how best to package internal dependencies for deployment. :) I feel like requiring one to munge `PATH`, or `sudo` something in order to install and run a web app is a bit of an anti-pattern. Instead, I like to install any extra dependencies within the project tree, and symlink any binaries inside `bin/`. That way, Elm is completely encapsulated within the larger project as an implementation detail. This is definitely just my personal opinion, not trying to force it on others! But I would like the flexibility to be able to do it this way.

If it helps, I can give another common example of where having this configuration option would be helpful. Imagine that you have many different Rails projects on your development machine, many of them composing Elm. A new version of Elm is released, and you want to upgrade each site to it, one at a time, over the course of weeks or months. With a globally-installed Elm, this is impractical. With an Elm that lives inside of each project directory (or many versions installed in e.g. ~/.elm/, etc),  this is a non-issue, provided you can configure the path.

What do you think?

**Comment by fbonetti** [comment]
Yeah that makes perfect. I'll take a look at the PR.

**Comment by fbonetti** [comment]
This is now available in version 0.2.0:

https://rubygems.org/gems/elm-compiler/versions/0.2.0

**Comment by botandrose** [comment]
Thank you very much for taking time on this! :tada: :tada: :tada:

With this in place, I'll revisit https://github.com/fbonetti/elm-rails/pull/4 ... see if I can merge it with the other PR and get a test going.

**Comment by fbonetti** [comment]
@botandrose Thank for being patient 😅 It looks like there are 2 PRs open elm-rails that integrate Elm into sprockets. Have you looked at the other one? Ideally elm-rails should work with both Rails 4 and Rails 5

**Comment by botandrose** [comment]
Yes, my PR works with sprockets-rails 2.0, and the other works with 3.0. My current plan is to first get a test passing with what I have, then use something like Appraisal to test both Rails 4 and Rails 5 setups, then merge in Mario's work in the other PR. Sound good to you?

**Comment by fbonetti** [comment]
Sounds great! Thanks for your help. I apologize for taking so long to
respond to your PRs. I just started freelancing recently so I finally now
have the time to keep up with my open source projects

**Comment by botandrose** [comment]
No worries, I maintain a few projects myself, so I know how it is. :)
